<?php
function SaveTechnical($mineid,$notice=null){
echo $mineid;
exit();
$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataDigreturnrate";
	$basedata35->data35P1=$_POST[basedataDigreturnrate_bef1];
	$basedata35->data35P2=$_POST[basedataDigreturnrate_bef2];
	$basedata35->data35P3=$_POST[basedataDigreturnrate_bef3];
	$basedata35->data35Aj1=$_POST[basedataDigreturnrate_pre1];
	$basedata35->data35Aj2=$_POST[basedataDigreturnrate_pre2];
	$basedata35->data35Aj3=$_POST[basedataDigreturnrate_pre3];
	$basedata35->data35Aj4=$_POST[basedataDigreturnrate_pre4];
	$basedata35->data35Aj5=$_POST[basedataDigreturnrate_pre5];
	$basedata35->data35As1=$_POST[basedataDigreturnrate_pre1real];
	$basedata35->data35As2=$_POST[basedataDigreturnrate_pre2real];
	$basedata35->data35As3=$_POST[basedataDigreturnrate_pre3real];
	$basedata35->data35As4=$_POST[basedataDigreturnrate_pre4real];
	$basedata35->data35As5=$_POST[basedataDigreturnrate_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataResourcesTotal";
	$basedata35->data35P1=$_POST[basedataResourcesTotal_bef1];
	$basedata35->data35P2=$_POST[basedataResourcesTotal_bef2];
	$basedata35->data35P3=$_POST[basedataResourcesTotal_bef3];
	$basedata35->data35Aj1=$_POST[basedataResourcesTotal_pre1];
	$basedata35->data35Aj2=$_POST[basedataResourcesTotal_pre2];
	$basedata35->data35Aj3=$_POST[basedataResourcesTotal_pre3];
	$basedata35->data35Aj4=$_POST[basedataResourcesTotal_pre4];
	$basedata35->data35Aj5=$_POST[basedataResourcesTotal_pre5];
	$basedata35->data35As1=$_POST[basedataResourcesTotal_pre1real];
	$basedata35->data35As2=$_POST[basedataResourcesTotal_pre2real];
	$basedata35->data35As3=$_POST[basedataResourcesTotal_pre3real];
	$basedata35->data35As4=$_POST[basedataResourcesTotal_pre4real];
	$basedata35->data35As5=$_POST[basedataResourcesTotal_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataResourcesHave";
	$basedata35->data35P1=$_POST[basedataResourcesHave_bef1];
	$basedata35->data35P2=$_POST[basedataResourcesHave_bef2];
	$basedata35->data35P3=$_POST[basedataResourcesHave_bef3];
	$basedata35->data35Aj1=$_POST[basedataResourcesHave_pre1];
	$basedata35->data35Aj2=$_POST[basedataResourcesHave_pre2];
	$basedata35->data35Aj3=$_POST[basedataResourcesHave_pre3];
	$basedata35->data35Aj4=$_POST[basedataResourcesHave_pre4];
	$basedata35->data35Aj5=$_POST[basedataResourcesHave_pre5];
	$basedata35->data35As1=$_POST[basedataResourcesHave_pre1real];
	$basedata35->data35As2=$_POST[basedataResourcesHave_pre2real];
	$basedata35->data35As3=$_POST[basedataResourcesHave_pre3real];
	$basedata35->data35As4=$_POST[basedataResourcesHave_pre4real];
	$basedata35->data35As5=$_POST[basedataResourcesHave_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataResourcesAvailable";
	$basedata35->data35P1=$_POST[basedataResourcesAvailable_bef1];
	$basedata35->data35P2=$_POST[basedataResourcesAvailable_bef2];
	$basedata35->data35P3=$_POST[basedataResourcesAvailable_bef3];
	$basedata35->data35Aj1=$_POST[basedataResourcesAvailable_pre1];
	$basedata35->data35Aj2=$_POST[basedataResourcesAvailable_pre2];
	$basedata35->data35Aj3=$_POST[basedataResourcesAvailable_pre3];
	$basedata35->data35Aj4=$_POST[basedataResourcesAvailable_pre4];
	$basedata35->data35Aj5=$_POST[basedataResourcesAvailable_pre5];
	$basedata35->data35As1=$_POST[basedataResourcesAvailable_pre1real];
	$basedata35->data35As2=$_POST[basedataResourcesAvailable_pre2real];
	$basedata35->data35As3=$_POST[basedataResourcesAvailable_pre3real];
	$basedata35->data35As4=$_POST[basedataResourcesAvailable_pre4real];
	$basedata35->data35As5=$_POST[basedataResourcesAvailable_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataProduceScale";
	$basedata35->data35P1=$_POST[basedataProduceScale_bef1];
	$basedata35->data35P2=$_POST[basedataProduceScale_bef2];
	$basedata35->data35P3=$_POST[basedataProduceScale_bef3];
	$basedata35->data35Aj1=$_POST[basedataProduceScale_pre1];
	$basedata35->data35Aj2=$_POST[basedataProduceScale_pre2];
	$basedata35->data35Aj3=$_POST[basedataProduceScale_pre3];
	$basedata35->data35Aj4=$_POST[basedataProduceScale_pre4];
	$basedata35->data35Aj5=$_POST[basedataProduceScale_pre5];
	$basedata35->data35As1=$_POST[basedataProduceScale_pre1real];
	$basedata35->data35As2=$_POST[basedataProduceScale_pre2real];
	$basedata35->data35As3=$_POST[basedataProduceScale_pre3real];
	$basedata35->data35As4=$_POST[basedataProduceScale_pre4real];
	$basedata35->data35As5=$_POST[basedataProduceScale_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataProduceDig";
	$basedata35->data35P1=$_POST[basedataProduceDig_bef1];
	$basedata35->data35P2=$_POST[basedataProduceDig_bef2];
	$basedata35->data35P3=$_POST[basedataProduceDig_bef3];
	$basedata35->data35Aj1=$_POST[basedataProduceDig_pre1];
	$basedata35->data35Aj2=$_POST[basedataProduceDig_pre2];
	$basedata35->data35Aj3=$_POST[basedataProduceDig_pre3];
	$basedata35->data35Aj4=$_POST[basedataProduceDig_pre4];
	$basedata35->data35Aj5=$_POST[basedataProduceDig_pre5];
	$basedata35->data35As1=$_POST[basedataProduceDig_pre1real];
	$basedata35->data35As2=$_POST[basedataProduceDig_pre2real];
	$basedata35->data35As3=$_POST[basedataProduceDig_pre3real];
	$basedata35->data35As4=$_POST[basedataProduceDig_pre4real];
	$basedata35->data35As5=$_POST[basedataProduceDig_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataProduceFactory";
	$basedata35->data35P1=$_POST[basedataProduceFactory_bef1];
	$basedata35->data35P2=$_POST[basedataProduceFactory_bef2];
	$basedata35->data35P3=$_POST[basedataProduceFactory_bef3];
	$basedata35->data35Aj1=$_POST[basedataProduceFactory_pre1];
	$basedata35->data35Aj2=$_POST[basedataProduceFactory_pre2];
	$basedata35->data35Aj3=$_POST[basedataProduceFactory_pre3];
	$basedata35->data35Aj4=$_POST[basedataProduceFactory_pre4];
	$basedata35->data35Aj5=$_POST[basedataProduceFactory_pre5];
	$basedata35->data35As1=$_POST[basedataProduceFactory_pre1real];
	$basedata35->data35As2=$_POST[basedataProduceFactory_pre2real];
	$basedata35->data35As3=$_POST[basedataProduceFactory_pre3real];
	$basedata35->data35As4=$_POST[basedataProduceFactory_pre4real];
	$basedata35->data35As5=$_POST[basedataProduceFactory_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataSepareturnrate";
	$basedata35->data35P1=$_POST[basedataSepareturnrate_bef1];
	$basedata35->data35P2=$_POST[basedataSepareturnrate_bef2];
	$basedata35->data35P3=$_POST[basedataSepareturnrate_bef3];
	$basedata35->data35Aj1=$_POST[basedataSepareturnrate_pre1];
	$basedata35->data35Aj2=$_POST[basedataSepareturnrate_pre2];
	$basedata35->data35Aj3=$_POST[basedataSepareturnrate_pre3];
	$basedata35->data35Aj4=$_POST[basedataSepareturnrate_pre4];
	$basedata35->data35Aj5=$_POST[basedataSepareturnrate_pre5];
	$basedata35->data35As1=$_POST[basedataSepareturnrate_pre1real];
	$basedata35->data35As2=$_POST[basedataSepareturnrate_pre2real];
	$basedata35->data35As3=$_POST[basedataSepareturnrate_pre3real];
	$basedata35->data35As4=$_POST[basedataSepareturnrate_pre4real];
	$basedata35->data35As5=$_POST[basedataSepareturnrate_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataValue";
	$basedata35->data35P1=$_POST[basedataValue_bef1];
	$basedata35->data35P2=$_POST[basedataValue_bef2];
	$basedata35->data35P3=$_POST[basedataValue_bef3];
	$basedata35->data35Aj1=$_POST[basedataValue_pre1];
	$basedata35->data35Aj2=$_POST[basedataValue_pre2];
	$basedata35->data35Aj3=$_POST[basedataValue_pre3];
	$basedata35->data35Aj4=$_POST[basedataValue_pre4];
	$basedata35->data35Aj5=$_POST[basedataValue_pre5];
	$basedata35->data35As1=$_POST[basedataValue_pre1real];
	$basedata35->data35As2=$_POST[basedataValue_pre2real];
	$basedata35->data35As3=$_POST[basedataValue_pre3real];
	$basedata35->data35As4=$_POST[basedataValue_pre4real];
	$basedata35->data35As5=$_POST[basedataValue_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataFee";
	$basedata35->data35P1=$_POST[basedataFee_bef1];
	$basedata35->data35P2=$_POST[basedataFee_bef2];
	$basedata35->data35P3=$_POST[basedataFee_bef3];
	$basedata35->data35Aj1=$_POST[basedataFee_pre1];
	$basedata35->data35Aj2=$_POST[basedataFee_pre2];
	$basedata35->data35Aj3=$_POST[basedataFee_pre3];
	$basedata35->data35Aj4=$_POST[basedataFee_pre4];
	$basedata35->data35Aj5=$_POST[basedataFee_pre5];
	$basedata35->data35As1=$_POST[basedataFee_pre1real];
	$basedata35->data35As2=$_POST[basedataFee_pre2real];
	$basedata35->data35As3=$_POST[basedataFee_pre3real];
	$basedata35->data35As4=$_POST[basedataFee_pre4real];
	$basedata35->data35As5=$_POST[basedataFee_pre5real];
	$basedata35->add();
	
	$basedata35 = new Data35;
	$basedata35->mineId=$mineid;
	$basedata35->data35name="basedataProfit";
	$basedata35->data35P1=$_POST[basedataProfit_bef1];
	$basedata35->data35P2=$_POST[basedataProfit_bef2];
	$basedata35->data35P3=$_POST[basedataProfit_bef3];
	$basedata35->data35Aj1=$_POST[basedataProfit_pre1];
	$basedata35->data35Aj2=$_POST[basedataProfit_pre2];
	$basedata35->data35Aj3=$_POST[basedataProfit_pre3];
	$basedata35->data35Aj4=$_POST[basedataProfit_pre4];
	$basedata35->data35Aj5=$_POST[basedataProfit_pre5];
	$basedata35->data35As1=$_POST[basedataProfit_pre1real];
	$basedata35->data35As2=$_POST[basedataProfit_pre2real];
	$basedata35->data35As3=$_POST[basedataProfit_pre3real];
	$basedata35->data35As4=$_POST[basedataProfit_pre4real];
	$basedata35->data35As5=$_POST[basedataProfit_pre5real];
	$basedata35->add();
?>